mode: live
safe_mode:
  enabled: true
  hold_on_startup: false
  require_double_confirmation: true
venues:
  binance:
    name: binance
    trading_pairs: ["BTC/USDT", "ETH/USDT"]
    taker_fee_bps: 5.0
    maker_fee_bps: 0.75
    simulate: true
  okx:
    name: okx
    trading_pairs: ["BTC/USDT", "ETH/USDT"]
    taker_fee_bps: 4.8
    maker_fee_bps: 0.7
    simulate: true
risk:
  max_position_usd: 6000
  max_single_order_usd: 400
  max_daily_drawdown_usd: 800
  stop_loss_bps: 35
scheduler:
  max_workers: 4
  tick_interval_ms: 120
storage:
  journal_path: data/live_journal.sqlite3
  archive_path: data/archive/live
