mode: testnet
safe_mode:
  enabled: true
  hold_on_startup: true
  require_double_confirmation: true
venues:
  binance:
    name: binance
    trading_pairs: ["BTC/USDT", "ETH/USDT"]
    taker_fee_bps: 6.0
    maker_fee_bps: 0.9
    simulate: true
  okx:
    name: okx
    trading_pairs: ["BTC/USDT", "ETH/USDT"]
    taker_fee_bps: 5.5
    maker_fee_bps: 0.8
    simulate: true
risk:
  max_position_usd: 4000
  max_single_order_usd: 250
  max_daily_drawdown_usd: 500
  stop_loss_bps: 40
scheduler:
  max_workers: 4
  tick_interval_ms: 150
storage:
  journal_path: data/testnet_journal.sqlite3
  archive_path: data/archive/testnet
