name: CI

on:
  push:
    branches: ["*"]
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Ruff
        run: ruff check .
        continue-on-error: true
      - name: Mypy
        run: mypy propbot
        continue-on-error: true
      - name: Pytest
        run: pytest
        continue-on-error: true
